# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'nixflymc'
primary_region = 'den'

[[services]]
  internal_port = 25565
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0

[[services.ports]]
  port = 25565

[[vm]]
  memory = "4GB"
  cpus = 2
  cpu_kind = "shared"

