name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-24.05-small
          extra_nix_config: |
            experimental-features = nix-command flakes
      - run: nix --log-format raw -L build .#defaultDockerContainer.x86_64-linux
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-24.05-small
          extra_nix_config: |
            experimental-features = nix-command flakes
      - run: nix --log-format raw -L run .#deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
